language: python

python: 3.6
env:
  - TOXENV=py36

install:
  - pip install -U tox

script:
  - tox

deploy:
  provider: pypi
  distributions: sdist
  user: harrisont
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: harrisont/python_boilerplate
    condition: $TOXENV == py36
